DATABASE: "host=104.214.169.124 user=lighting password=[E~P2VZnWPzU<&a^ dbname=portal port=5432 sslmode=disable"
CLOUDFLARE_TURNSTILE_SECRET: "1x0000000000000000000000000000000AA"
JWT_PUBLIC_KEY: |
    -----BEGIN PUBLIC KEY-----
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAhNjpbVDNFp9gq7ZdPfdz
    eH2oZwT4JD3DAKaCeeIm5lZpz3qtlaTjjBYVohExDidUL+h15FGqHHPFqr+mQhD+
    TCflhXumXwUybqgFCQK+R65Pqt0EvYze2TTiIDdSLfNI8sHuZg3HjHhNi6BagbR+
    ziYEM/I4KrSWgjGrGd/NEhRK4bDsaF9QXYy062mybcZnBv+mZ4UKqOgGtlvkAF5L
    k8ah33WYep2qigkpFqjFzdN48ColFvFk6F6fyqnfsCGRi+eKEJRe83Y0I1hHPUd6
    KQqfevw5LA3k8LYlKvzsTnNaGU0xhFw49VyodevG1NT6pT1950jtt+gYxxZh8Mrb
    gQIDAQAB
    -----END PUBLIC KEY-----
JWT_PRIVATE_KEY: |
    -----BEGIN PRIVATE KEY-----
    MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCE2OltUM0Wn2Cr
    tl0993N4fahnBPgkPcMApoJ54ibmVmnPeq2VpOOMFhWiETEOJ1Qv6HXkUaocc8Wq
    v6ZCEP5MJ+WFe6ZfBTJuqAUJAr5Hrk+q3QS9jN7ZNOIgN1It80jywe5mDceMeE2L
    oFqBtH7OJgQz8jgqtJaCMasZ380SFErhsOxoX1BdjLTrabJtxmcG/6ZnhQqo6Aa2
    W+QAXkuTxqHfdZh6naqKCSkWqMXN03jwKiUW8WToXp/Kqd+wIZGL54oQlF7zdjQj
    WEc9R3opCp96/DksDeTwtiUq/OxOc1oZTTGEXDj1XKh168bU1PqlPX3nSO236BjH
    FmHwytuBAgMBAAECggEAAQ73YShtJzp9hdtjR8ydGL8rjyfneuZxE3lq0wzIZuUW
    XRGq/g+9GQ8jUfzAFCRKaUKkDyh6v1T0JLr32KaTrXNTQqqBtgJvwe5IcqducQTE
    XBCnFS7g/FW4XYMDU8a7SeUzVeXTNV0kr7GcjFRYqaInk2sLzoSiKbG6nW9T43Uk
    qUaJLInF0vPs9813ZmP8QOhczfcv/Tiqt3aEFdf0IVR8qygzRvISRLjuGGKxVosZ
    ArS6F/fL4WZdgISeHD+1GOVrnZU6YnI22pEY0Z8T0qtTCp06iQOTJXeUXgdsZDd7
    LuhPedoZHcMd9CcyE7ClSYTBp5u6bvcc7xoaUj5YIQKBgQC5ZKMnAjnI6Zw79zrP
    9tVKiRBSHjclcDuW1iJeeOLr/HZTXzNdqEOBvgrE/QjrYxElPoNX5J0oE8djJanX
    uBNivV7a9yj3iXY9xV2lFsy4wqYnT6pJZbkqB8ZR/kmy3d2Y6k5lGyiOGPfFr8ud
    pck04GqgvfCahJHVtsYn30ZTKQKBgQC3cTDZi5ilP5qNMBv96GmlVArDAc+so/cR
    w1kzpGNx6yxaxMvx3TZYx8+UErOEgULU5K+kko59cv1Clb5FzsyQEtXlG8i70VDK
    bqwVaz/JnREFZUi2Now3AhMfmkuShIDN0lac8GWbuy/U1RZTE2Z7k5zEogHvqeBn
    ExLRY/bomQKBgAj9clPv7bFqcqMNyBJRm+IzZ1E0GeR83sbft2bxYb+jzHEairkd
    8bgW6RrIUmhns2sk7uWSNnS9EMwkBWpqiLYfDLx9g8UNK2iva20X//FtrvT1DgLl
    Jed93QYY2KYN0DMcGZUZjgvl9g3mCm+onGst/r2wuDwl9ZRxeoZwc06RAoGBAJA9
    DUcRD65nq5N2j5v/QgqAYZHh+7RonJ2394y2pobtfsvEUARWhyQZwGtSpRr8NFuH
    kWAa6LVVVDQl4B2ttIVYeh0S0qxzsk3p5Z9V3CsgOEEA2cKEc43RMM45mVCUpV6x
    E++EyrA/6CU2g75A0+U5NRwbsuAKt+r0QWipbHyJAoGAdVfHvpQmgpNvB7fl6vqm
    CnCgk2/5YUMecow2aTOQsx3GjOZYS3pJ599TQxMu1x78E1q6SnSv9Snwac01Un3V
    khOPu6YAKZksVGHnTCkArs+fogK30/74josszUCIU/PtWAkJ5e89SfmB4u9lX4Wn
    7Oyz6GRwtjfua7/piapKZWc=
    -----END PRIVATE KEY-----
SOURCE_URL: file://~/Projects/pnnh/rust
STORAGE_URL: file://~/temp/rust
BLOG_URL: file://~/Projects/github/blog
REDIS_URL: "104.214.169.124:6379 xb!B2tf*eKc56M"
PUBLIC_SELF_URL: "https://huable.local/portal"